- authn/builtin_provider.go
- cli/cmd/namespaces.go
- doc/HOWTO.md
- doc/swagger.json
- model/types.go
- model/validate.go
- namespace/namespace_api.go
- namespace/namespace_api_test.go
- namespace/namespace_manager.go
- namespace/namespace_manager_test.go
- secret/secret_api.go
- secret/secret_api_test.go
- secret/secret_manager.go
- secret/secret_manager_test.go
- server/server.go
- vds/transform.go
* Namespaces cli command
* Users are created under "/users"
* Secrets are created under "/secrets"
> Finished namespace feature

- README.md
> Add slack info to README

- .travis.yml
- Makefile
- README.md
- model/validate.go
- secret/secret_api_test.go
- secret/secret_manager_test.go
> Issue #28 Add travis-ci system

- config/config_test_util.go
- config/load.go
- server/server.go
- util/util.go
- util/util_test.go
> Add configuration port validation

- .gitignore
- .travis.yml
- ci/coverage.sh
> Improve test coverage results

- server/server.go
- util/util.go
> Improve CheckPort validation

- README.md
- doc/HOWTO.md
> Minor updates to README and HOWTO

- doc/HOWTO.md
> Minor fix in HOWTO

- .travis.yml
- ci/coverage.sh
- create a coverage profile for each package
- concatenate all coverage into a single one
> Refactor unittest coverage

- doc/HOWTO.md
> Minor fix to HOWTO

- doc/HOWTO.md
> Additional fixes in HOWTO

- doc/HOWTO.md
> Improvements to HOWTO

- authn/authn_api_test.go
- authn/authn_manager.go
- authn/authn_manager_test.go
- authn/builtin_provider.go
- authn/builtin_provider_test.go
- authz/authz_api.go
- authz/authz_api_test.go
- authz/authz_manager.go
- authz/authz_manager_test.go
- cli/cmd/authz_policies.go
- cli/cmd/namespaces.go
- cli/cmd/secrets.go
- cli/cmd/users.go
- context/module_init_context.go
- doc/swagger.json
- model/types.go
- model/util.go
- model/validate.go
- namespace/namespace_manager.go
- namespace/namespace_manager_test.go
- secret/secret_api_test.go
- secret/secret_manager.go
- secret/secret_manager_test.go
- server/server.go
- vds/datastore_util.go
- vds/transform.go
* Ability to CRUD users with roles
* Ability to CRUD authorization policies in a namespace
* Ability to determine whether an operation is granted access
Authorization is still not checked/enforced on access path - will be done in a
separate commit.
> Authorization infrastructure

- authn/authn_api.go
- authn/authn_manager.go
- authn/authn_manager_test.go
- authz/authz_api.go
- authz/authz_manager.go
- authz/authz_manager_test.go
- context/authorization_manager.go
- context/context_test_util.go
- context/module_init_context.go
- context/request_context.go
- doc/HOWTO.md
- doc/swagger.json
- namespace/namespace_api.go
- namespace/namespace_api_test.go
- namespace/namespace_manager.go
- namespace/namespace_manager_test.go
- secret/secret_api.go
- secret/secret_manager.go
- secret/secret_manager_test.go
- server/server.go
- server/server_api_test.go
- util/http_filter.go
- util/http_filter_test.go
* Authorization is wired and enforced
* Howto explains how to use
> Authorization feature is enabled

- doc/HOWTO.md
> HOWTO fixes

- cli/cmd/login.go
- cli/cmd/secrets.go
- doc/HOWTO.md
- doc/swagger.json
- model/types.go
- model/util.go
- model/validate.go
- secret/data_st.go
- secret/data_st_api_test.go
- secret/data_st_test.go
- secret/rsa_private_key_st.go
- secret/rsa_private_key_st_api_test.go
- secret/rsa_private_key_st_test.go
- secret/secret_api_test.go
- secret/secret_manager_test.go
- secret/x509_certificate_st.go
- secret/x509_certificate_st_api_test.go
- secret/x509_certificate_st_test.go
- vds/transform.go
Two new secret types have been added:
* RSAPrivateKey
* X509Certificate
With tests and cli-commands.
HOW-TO has been updated.
> Two new secret types

- doc/HOWTO.md
- secret/data_st.go
- secret/rsa_private_key_st.go
- secret/secret_manager.go
- secret/secret_type.go
- secret/x509_certificate_st.go
- util/util.go
Two improvements:
* User must have access to the private key it uses to create a cert
* Certificate is signed by the VSM server acting as a CA
> X509CertificateSecret improvements

- doc/HOWTO.md
> Fixed how-to

- doc/HOWTO.md
> Fixed howto bug

- Makefile
- authn/builtin_provider_test.go
- authz/authz_manager.go
- config/config.go
- namespace/namespace_manager.go
- util/errors.go
- util/util.go
- vds/datastore_adapter.go
- vds/inmemory_ds.go
- vds/mongodb_ds.go
To use:
* get mongo container from https://hub.docker.com/_/mongo/ and start it
* in "config.yaml", under "dataStore", set type to "MongoDBDataStore" and
add "connectionString" property with value set to mongo container IP address
> MongoDB DataStoreAdapter

- authn/builtin_provider.go
- authz/authz_manager.go
- authz/authz_manager_test.go
- namespace/namespace_manager.go
- secret/data_st.go
- secret/rsa_private_key_st.go
- secret/x509_certificate_st.go
- vds/datastore_adapter.go
- vds/inmemory_ds.go
- vds/mongodb_ds.go
CreateEntry instead of WriteEntry to better reflect semantics and to improve
performance. Implementations have been updated.
> DataStoreAdapter refactored

- doc/HOWTO.md
> Edited how-to's config section

- .travis.yml
- Dockerfile
- Makefile
> Add docker image build

- doc/HOWTO.md
- vds/datastore_adapter.go
- vds/datastore_util.go
- vds/inmemory_ds.go
- vds/inmemory_ds_test.go
- vds/mongodb_ds.go
- vks/keystore_adapter.go
Also slight change to DataStoreAdapter interface.
> Documentation of persistent data and key stores

- config/config_test_util.go
- doc/HOWTO.md
- vks/virtual_key_store.go
- vks/virtual_key_store_test.go
Writes and reads from key stores now happen concurrently.
> Concurrent write/read from key stores

- Makefile
- authn/builtin_provider.go
- doc/HOWTO.md
- namespace/namespace_manager.go
- vds/cassandra_ds.go
> Cassandra DataStoreAdapter

- doc/HOWTO.md
- vds/cassandra_ds.go
- vds/mongodb_ds.go
Added support for a custom MongoDB write concern.
Documentation has been updated.
> MongoDB DataStoreAdapter custom write concern
